version: '3.7'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mudaark_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mudaark_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mudaark
      POSTGRES_USER: mudaark
      POSTGRES_PASSWORD: mudaark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mudaark_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=django-insecure-afe7j%5h*(iph75synbd=_xjx#8ow2_c1%1mbt4@zww%o#@gft
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=mudaark.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://mudaark:mudaark@db:5432/mudaark
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=mudaark
      - AWS_S3_ENDPOINT_URL=http://localhost:9000
    networks:
      - mudaark_network

  celery:
    build: .
    command: celery -A mudaark worker --loglevel=info -P eventlet
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - mudaark_network

volumes:
  postgres_data:
  minio_data:

networks:
  mudaark_network:
    driver: bridge
