# Generated by Django 5.1.3 on 2024-11-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('processing', 'В процессе'), ('completed', 'Обработан'), ('error', 'Ошибка')], default='processing', max_length=50),
        ),
    ]
