# Generated by Django 5.1.3 on 2024-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_analysis_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Обработан', 'Обработан'), ('Ошибка', 'Ошибка')], default='processing', max_length=50),
        ),
    ]
