# Generated by Django 5.1.3 on 2024-11-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_analysis_result_alter_file_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
