# Generated by Django 5.1.3 on 2024-11-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В процессе'), ('completed', 'Обработан'), ('error', 'Ошибка')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
